export const hackathons = [
    {
      id: "agentforce",
      title: "Agentforce Virtual Hackathon",
      timeLeft: "20 days left",
      location: "Online",
      prize: "₹1,40,000 in prizes",
      participants: "5922 participants",
      tags: ["Salesforce", "Machine Learning", "Beginner Friendly"],
      date: "Mar 05 - Apr 30, 2025",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/278/434/datas/medium_square.png",
    deadline: "May 1, 2025 @ 4:30am GMT+5:30",
    rules: [
      "Above legal age of majority in country of residence",
      "Only specific countries/territories included",
      "Quebec is excluded",
    ],
    prizes: [
      { title: "Overall Grand Prize", amount: "$50,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Most Creative", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Most Impactful", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Best Demo Delivery", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Best Use of Slack Prize", amount: "$25,000 in cash", winners: "1 winner" },
      { title: "People's Choice (Public Voting)", amount: "$5,000 in cash", winners: "1 winner" },
    ],
    judges: [
      { name: "Praneetha", title: "SVP, Technical Audience Relations | Salesforce", image: "judge1.jpg" },
      { name: "Sowjanya", title: "Director, Product Marketing | Salesforce", image: "judge2.jpg" },
      { name: "Prasana", title: "Developer Advocate Director | Salesforce", image: "judge3.jpg" },
    ],
    },
    {
      id: "meta",
      title: "Meta Horizon Creator Competition",
      timeLeft: "15 days left",
      location: "Online",
      prize: "₹50,000 in prizes",
      participants: "3500 participants",
      tags: ["Meta", "AR/VR", "Creative Tech"],
      date: "Apr 01 - Apr 25, 2025",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/295/852/datas/medium_square.jpg",
      deadline: "May 1, 2025 @ 4:30am GMT+5:30",
    rules: [
      "Above legal age of majority in country of residence",
      "Only specific countries/territories included",
      "Quebec is excluded",
    ],
    prizes: [
      { title: "Overall Grand Prize", amount: "$50,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Most Creative", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Most Impactful", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Best Demo Delivery", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Best Use of Slack Prize", amount: "$25,000 in cash", winners: "1 winner" },
      { title: "People's Choice (Public Voting)", amount: "$5,000 in cash", winners: "1 winner" },
    ],
    judges: [
      { name: "Praneetha", title: "SVP, Technical Audience Relations | Salesforce", image: "judge1.jpg" },
      { name: "Sowjanya", title: "Director, Product Marketing | Salesforce", image: "judge2.jpg" },
      { name: "Prasana", title: "Developer Advocate Director | Salesforce", image: "judge3.jpg" },
    ],
    },
    {
        id: "metax",
      title: "Meta Hack XR Challenge",
      timeLeft: "12 days left",
      location: "Online",
      prize: "₹75,000 in prizes",
      participants: "4000 participants",
      tags: ["Meta", "XR", "Beginner"],
      date: "Apr 01 - Apr 20, 2025",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/319/065/datas/medium_square.png",
      deadline: "May 1, 2025 @ 4:30am GMT+5:30",
    rules: [
      "Above legal age of majority in country of residence",
      "Only specific countries/territories included",
      "Quebec is excluded",
    ],
    prizes: [
      { title: "Overall Grand Prize", amount: "$50,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Most Creative", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Most Impactful", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Best Demo Delivery", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Best Use of Slack Prize", amount: "$25,000 in cash", winners: "1 winner" },
      { title: "People's Choice (Public Voting)", amount: "$5,000 in cash", winners: "1 winner" },
    ],
    judges: [
      { name: "Praneetha", title: "SVP, Technical Audience Relations | Salesforce", image: "judge1.jpg" },
      { name: "Sowjanya", title: "Director, Product Marketing | Salesforce", image: "judge2.jpg" },
      { name: "Prasana", title: "Developer Advocate Director | Salesforce", image: "judge3.jpg" },
    ],
    },
    {
        id: "cloud",
      title: "Cloud Builder Sprint",
      timeLeft: "10 days left",
      location: "Online",
      prize: "₹30,000 in prizes",
      participants: "2800 participants",
      tags: ["Cloud", "DevOps", "Infrastructure"],
      date: "Apr 01 - Apr 15, 2025",
      image: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/003/219/991/datas/medium_square.png",
      deadline: "May 1, 2025 @ 4:30am GMT+5:30",
    rules: [
      "Above legal age of majority in country of residence",
      "Only specific countries/territories included",
      "Quebec is excluded",
    ],
    prizes: [
      { title: "Overall Grand Prize", amount: "$50,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Most Creative", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Most Impactful", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Honorable Mention: Best Demo Delivery", amount: "$20,000 in cash", winners: "1 winner" },
      { title: "Best Use of Slack Prize", amount: "$25,000 in cash", winners: "1 winner" },
      { title: "People's Choice (Public Voting)", amount: "$5,000 in cash", winners: "1 winner" },
    ],
    judges: [
      { name: "Praneetha", title: "SVP, Technical Audience Relations | Salesforce", image: "judge1.jpg" },
      { name: "Sowjanya", title: "Director, Product Marketing | Salesforce", image: "judge2.jpg" },
      { name: "Prasana", title: "Developer Advocate Director | Salesforce", image: "judge3.jpg" },
    ],
    },
  ];